SELECT B.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(B.PRICE * S.SALES) AS TOTAL_SALES
FROM (SELECT * FROM BOOK_SALES WHERE SALES_DATE LIKE '2022-01%') S 
    JOIN BOOK B ON S.BOOK_ID = B.BOOK_ID 
    JOIN AUTHOR A ON A.AUTHOR_ID = B.AUTHOR_ID 
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID, B.CATEGORY DESC;