WITH INFO AS (
    SELECT 
        C.CAR_ID, 
        C.DAILY_FEE, 
        H.HISTORY_ID,
        DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS PERIOD,
        CASE 
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 >= 7 THEN '7일 이상'
            ELSE 'NONE'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
    JOIN CAR_RENTAL_COMPANY_CAR C ON H.CAR_ID = C.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT I.HISTORY_ID, 
    ((100 - IFNULL(P.DISCOUNT_RATE, 0)) * I.DAILY_FEE * I.PERIOD) DIV 100 AS FEE
FROM INFO I 
    LEFT JOIN (SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN WHERE CAR_TYPE = '트럭') P 
    ON I.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, I.HISTORY_ID DESC