-- 코드를 입력하세요
SELECT S.APNT_NO, P.PT_NAME, P.PT_NO, S.MCDP_CD, S.DR_NAME, S.APNT_YMD
FROM PATIENT P 
JOIN (
    SELECT D.DR_NAME, D.MCDP_CD, A.PT_NO, A.APNT_YMD, A.APNT_NO
    FROM DOCTOR D JOIN APPOINTMENT A ON D.DR_ID = A.MDDR_ID
    WHERE A.MCDP_CD = 'CS' AND A.APNT_CNCL_YN = 'N' AND A.APNT_YMD LIKE '2022-04-13%'
    ) S 
ON P.PT_NO = S.PT_NO
ORDER BY S.APNT_YMD
        

        