WITH RECURSIVE hour_table AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM hour_table WHERE HOUR < 23
)
SELECT h.HOUR, 
       COALESCE(COUNT(a.DATETIME), 0) AS COUNT
FROM hour_table h
LEFT JOIN ANIMAL_OUTS a ON h.HOUR = HOUR(a.DATETIME)
GROUP BY h.HOUR
ORDER BY h.HOUR;
