SELECT U.USER_ID, U.NICKNAME, SUM(UB.PRICE) AS TOTAL_SALES
FROM USED_GOODS_USER U JOIN USED_GOODS_BOARD UB ON U.USER_ID = UB.WRITER_ID
WHERE UB.STATUS = 'DONE'
GROUP BY UB.WRITER_ID
HAVING SUM(UB.PRICE) >= 700000
ORDER BY TOTAL_SALES