SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
WHERE R.MEMBER_ID IN (
    -- 리뷰를 가장 많이 작성한 회원 찾기
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(review_count)
        FROM (
            SELECT MEMBER_ID, COUNT(*) AS review_count
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) AS subquery
    )
)
ORDER BY REVIEW_DATE, REVIEW_TEXT;
