WITH REVIEW_CTE AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_COUNT
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
),
MAX_REVIEW_COUNT AS (
    SELECT MAX(REVIEW_COUNT) AS MAX_COUNT
    FROM REVIEW_CTE
)

SELECT P.MEMBER_NAME, 
       R.REVIEW_TEXT,
       DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE P
JOIN REST_REVIEW R ON P.MEMBER_ID = R.MEMBER_ID
JOIN REVIEW_CTE CTE ON P.MEMBER_ID = CTE.MEMBER_ID
JOIN MAX_REVIEW_COUNT MRC ON CTE.REVIEW_COUNT = MRC.MAX_COUNT
ORDER BY REVIEW_DATE, R.REVIEW_TEXT;
