WITH REVIEW_RANK AS (SELECT MEMBER_ID, COUNT(REVIEW_ID) AS REVIEW_COUNT
                    FROM REST_REVIEW
                    GROUP BY MEMBER_ID)

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS REVIEW
LEFT JOIN REVIEW_RANK
ON REVIEW_RANK.MEMBER_ID = REVIEW.MEMBER_ID
LEFT JOIN (SELECT MEMBER_ID, MEMBER_NAME
          FROM MEMBER_PROFILE) AS PROFILE
ON PROFILE.MEMBER_ID = REVIEW.MEMBER_ID
WHERE REVIEW_COUNT = (SELECT MAX(REVIEW_COUNT)
                      FROM REVIEW_RANK)
ORDER BY REVIEW_DATE, REVIEW_TEXT;