WITH max_length_cte AS (
    SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX_LENGTH
    FROM ECOLI_DATA
    GROUP BY YEAR(DIFFERENTIATION_DATE)
)

SELECT YEAR(E.DIFFERENTIATION_DATE) AS YEAR, M.MAX_LENGTH - E.SIZE_OF_COLONY AS YEAR_DEV, E.ID
FROM ECOLI_DATA E JOIN max_length_cte M ON YEAR(E.DIFFERENTIATION_DATE) = M.YEAR
ORDER BY YEAR, YEAR_DEV