SELECT 
    YEAR(DIFFERENTIATION_DATE) AS YEAR, 
    (SELECT MAX(SIZE_OF_COLONY)  
     FROM ECOLI_DATA E
     WHERE YEAR(E.DIFFERENTIATION_DATE) = YEAR(ED.DIFFERENTIATION_DATE)
    ) - ED.SIZE_OF_COLONY AS YEAR_DEV, 
    ID
FROM ECOLI_DATA ED
ORDER BY YEAR, YEAR_DEV;
