-- 코드를 작성해주세요
SELECT G.SCORE, E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
FROM HR_DEPARTMENT D 
    JOIN HR_EMPLOYEES E ON D.DEPT_ID = E.DEPT_ID
    JOIN (SELECT SUM(SCORE) AS SCORE, EMP_NO FROM HR_GRADE GROUP BY EMP_NO) G 
        ON E.EMP_NO = G.EMP_NO
ORDER BY G.SCORE DESC
LIMIT 1
